"""empty message

Revision ID: 26e8c0fe3bc9
Revises: a6e0bdcd4c7d
Create Date: 2026-03-04 20:28:37.151092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e8c0fe3bc9'
down_revision = 'a6e0bdcd4c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('bio',
               existing_type=sa.NUMERIC(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
